In [2]:
import pandas as pd

file_path = './data/task.csv'

df = pd.read_csv(file_path)
print(df)
df.head(10)

          Код                                               Тема  \
0   HYDRA-535  Пробрасывать пользовательское распределение pa...
1   HYDRA-534   Гибридный рекомендатель с multi-channel feedback
2   HYDRA-532         Джоба в дженкинсе для расчёта динамики РВП
3   HYDRA-531                          Интеграция Hydra с Gamora
4   HYDRA-530                        Тестируем интеграцию с Jira
5   HYDRA-527               Поправить функцию _get_ui_rec_matrix
6   HYDRA-524                 Оптимизировать матрицу ItemFactors
7   HYDRA-523                                     Сортировка ЦПБ
8   HYDRA-520                           Закостылить параметр top
9   HYDRA-519     Сделать 'stable' конфигом по умолчанию в Гидре
10  HYDRA-518                Неудобно тестировать запись в redis
11  HYDRA-517            Улучшить рекомендации (первая итерация)
12  HYDRA-514           Добавить логирование в скрипты hydra/bin
13  HYDRA-513                          Поправить storage_backend
14  HYDRA-511  Перемешивание рекомендаций для старых пользова...
15  HYDRA-510                 Поправить скрипты bpr и и оценщика
16  HYDRA-509             Динамические персональные рекомендации
17  HYDRA-507           Навести порядок в prepare_data_for_hydra
18  HYDRA-506     Техдолг по логике /collection/recommendations/

        Компонент  Затрачено в часах
0         echidna                  1
1           hydra                  3
2   hydramatrices                  2
3   hydramagrices                  4
4           hydra                  2
5           hydra                 10
6           hydra                  2
7           hydra                  5
8           hydra                  2
9           hydra                  2
10  hydramatrices                  1
11          hydra                  7
12  hydramagrices                  5
13  hydramatrices                  2
14          hydra                  5
15    hydra_utils                 16
16          hydra                 10
17  hydramagrices                  3
18          hydra                 24

,Код,Тема,Компонент,Затрачено в часах
0,HYDRA-535,Пробрасывать пользовательское распределение pa...,echidna,1
1,HYDRA-534,Гибридный рекомендатель с multi-channel feedback,hydra,3
2,HYDRA-532,Джоба в дженкинсе для расчёта динамики РВП,hydramatrices,2
3,HYDRA-531,Интеграция Hydra с Gamora,hydramagrices,4
4,HYDRA-530,Тестируем интеграцию с Jira,hydra,2
5,HYDRA-527,Поправить функцию _get_ui_rec_matrix,hydra,10
6,HYDRA-524,Оптимизировать матрицу ItemFactors,hydra,2
7,HYDRA-523,Сортировка ЦПБ,hydra,5
8,HYDRA-520,Закостылить параметр top,hydra,2
9,HYDRA-519,Сделать 'stable' конфигом по умолчанию в Гидре,hydra,2

In [3]:
df.groupby(by=['Компонент'])['Затрачено в часах'].mean().to_frame().head()

               Затрачено в часах
Компонент
echidna                 1.000000
hydra                   6.545455
hydra_utils            16.000000
hydramagrices           4.000000
hydramatrices           1.666667

In [4]:
import numpy as np

agg_config = {'Затрачено в часах':{
    'mean_val': np.mean, 'max_val':np.max}
}

df.groupby(by=['Компонент']
)[
    ['Затрачено в часах']
].aggregate(
    agg_config
)

C:\Users\FilippKashket\Anaconda3\lib\site-packages\pandas\core\groupby\generic.py:1315: FutureWarning: using a dict with renaming is deprecated and will be removed in a future version
  return super(DataFrameGroupBy, self).aggregate(arg, *args, **kwargs)

                mean_val  max_val
Компонент
echidna         1.000000        1
hydra           6.545455       24
hydra_utils    16.000000       16
hydramagrices   4.000000        5
hydramatrices   1.666667        2